# Generated by Django 5.2.7 on 2025-10-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('position', models.CharField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('city', models.CharField()),
                ('department', models.CharField(choices=[('IT', 'IT department'), ('HR', 'HRdepartment'), ('STUDY', 'Study department'), ('SALES', 'Sales department')])),
            ],
        ),
    ]
