# Generated by Django 5.2.7 on 2025-10-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodim',
            name='department',
            field=models.CharField(choices=[('IT', 'IT department'), ('HR', 'HRdepartment'), ('STUDY', 'Study department'), ('SALES', 'Sales department')], default='IT'),
        ),
    ]
