# Generated by Django 5.2.7 on 2025-10-17 10:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_xodim_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xodim',
            options={'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterField(
            model_name='xodim',
            name='age',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(18)),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 10, 17, 10, 57, 28, 466429, tzinfo=datetime.timezone.utc)),
        ),
    ]
