# Generated by Django 5.2.7 on 2025-10-17 11:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_xodim_options_alter_xodim_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodim',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 10, 17, 11, 13, 59, 119907, tzinfo=datetime.timezone.utc)),
        ),
    ]
